[tool.codeflash]
# All paths are relative to this pyproject.toml's directory.
module-root = "backend"
tests-root = "backend"
test-framework = "pytest"
ignore-paths = []
formatter-cmds = ["black $file"]
